# Generated by Django 4.1 on 2024-05-29 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.anime'),
        ),
    ]
